package com.insp17.ytms.dtos;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class VideoMetadataDTO {

    // == CORE REQUIRED FIELDS ==
    @NotBlank(message = "Title is required")
    @Size(max = 100, message = "Title must not exceed 100 characters")
    private String title;

    @NotBlank(message = "Description is required")
    @Size(max = 5000, message = "Description must not exceed 5000 characters")
    private String description;

    @JsonProperty("video_type")
    private String videoType = "MAIN"; // MAIN or SHORT

    @JsonProperty("privacy_status")
    private String privacyStatus = "private"; // private, public, unlisted

    // == BASIC VIDEO INFORMATION ==
    private Set<String> tags;

    @JsonProperty("thumbnail_url")
    private String thumbnailUrl;

    private String category = "24"; // Default to Entertainment

    private String language = "en"; // Default to English

    private String license = "standard"; // Use "standard" or "creativeCommon"

    // == PRIVACY AND CONTENT SETTINGS ==
    @JsonProperty("age_restriction")
    private Boolean ageRestriction = false;

    @JsonProperty("made_for_kids")
    private Boolean madeForKids = false;

    // == SHORTS-SPECIFIC FIELDS ==
    @JsonProperty("is_short")
    private Boolean isShort = false;

    @JsonProperty("short_hashtags")
    private String shortHashtags; // For YouTube Shorts hashtags

    // == PUBLISHING OPTIONS ==
    @JsonProperty("scheduled_publish_time")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private LocalDateTime scheduledPublishTime;

    @JsonProperty("notify_subscribers")
    private Boolean notifySubscribers = true;

    @JsonProperty("publish_to_feed")
    private Boolean publishToFeed = true;

    // == MONETIZATION AND COMMUNITY ==
    private Boolean monetization = true;

    @JsonProperty("comments_enabled")
    private Boolean commentsEnabled = true;

    @JsonProperty("ratings_enabled")
    private Boolean ratingsEnabled = true;

    @JsonProperty("allow_embedding")
    private Boolean allowEmbedding = true;

    @JsonProperty("allow_video_responses")
    private Boolean allowVideoResponses = false;

    @JsonProperty("public_stats_viewable")
    private Boolean publicStatsViewable = true;

    // == PLAYLIST MANAGEMENT ==
    @JsonProperty("playlist_ids")
    private Set<String> playlistIds;

    // == ADVANCED FEATURES (MAIN VIDEOS ONLY) ==
    @JsonProperty("video_chapters")
    private List<VideoChapterDTO> videoChapters;

    @JsonProperty("end_screen")
    private String endScreen; // JSON string for end screen configuration

    private String cards; // JSON string for cards configuration

    // == SEO AND DISCOVERABILITY ==
    private Set<String> keywords; // Additional keywords for search optimization

    // == CAPTIONS AND SUBTITLES ==
    @JsonProperty("auto_generated_captions")
    private Boolean autoGeneratedCaptions = true;

    @JsonProperty("default_audio_language")
    private String defaultAudioLanguage = "en";

    // == GEOGRAPHIC AND RECORDING INFORMATION ==
    @JsonProperty("location_description")
    private String locationDescription;

    @JsonProperty("recording_date")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    private LocalDate recordingDate;

    @JsonProperty("recording_location")
    private String recordingLocation;

    @JsonProperty("video_latitude")
    private Double videoLatitude;

    @JsonProperty("video_longitude")
    private Double videoLongitude;

    // == CUSTOM THUMBNAIL ==
    @JsonProperty("custom_thumbnail_url")
    private String customThumbnailUrl;

    // == DEPRECATED/UNUSED FIELDS ==
    // These fields are kept for backward compatibility but are not actively used

    @Deprecated
    @JsonProperty("content_rating")
    private String contentRating; // Not used by YouTube API v3

    @Deprecated
    @JsonProperty("youtube_channel_id")
    private String youtubeChannelId; // Handled separately in upload process

    @Deprecated
    @JsonProperty("youtube_channel_name")
    private String youtubeChannelName; // Handled separately in upload process

    // == LEGACY SUPPORT ==
    @JsonProperty("recording_details")
    private RecordingDetailsDTO recordingDetails;

    // == HELPER METHODS ==

    /**
     * Validates if the metadata is suitable for YouTube Shorts
     */
    public boolean isValidForShorts() {
        return "SHORT".equals(videoType) || Boolean.TRUE.equals(isShort);
    }

    /**
     * Validates if the metadata is suitable for main/long-form videos
     */
    public boolean isValidForMainVideo() {
        return "MAIN".equals(videoType) || !Boolean.TRUE.equals(isShort);
    }

    /**
     * Gets the effective description including hashtags for Shorts
     */
    public String getEffectiveDescription() {
        StringBuilder desc = new StringBuilder();
        if (description != null) {
            desc.append(description);
        }

        if (isValidForShorts() && shortHashtags != null && !shortHashtags.trim().isEmpty()) {
            if (desc.length() > 0) {
                desc.append("\n\n");
            }
            desc.append(shortHashtags);
        }

        return desc.toString();
    }

    /**
     * Gets the effective thumbnail URL (custom takes priority)
     */
    public String getEffectiveThumbnailUrl() {
        return customThumbnailUrl != null && !customThumbnailUrl.trim().isEmpty()
                ? customThumbnailUrl
                : thumbnailUrl;
    }

    /**
     * Merges legacy recording details into main fields
     */
    public void mergeRecordingDetails() {
        if (recordingDetails != null) {
            if (this.locationDescription == null) {
                this.locationDescription = recordingDetails.getLocationDescription();
            }
            if (this.recordingDate == null) {
                this.recordingDate = recordingDetails.getRecordingDate();
            }
        }
    }

    /**
     * Creates recording details from main fields (for backward compatibility)
     */
    public void createRecordingDetails() {
        if (recordingDetails == null && (locationDescription != null || recordingDate != null)) {
            recordingDetails = new RecordingDetailsDTO(locationDescription, recordingDate);
        }
    }

    /**
     * Validates basic constraints
     */
    public void validate() {
        if (title == null || title.trim().isEmpty()) {
            throw new IllegalArgumentException("Title is required");
        }

        if (isValidForShorts()) {
            if (title.length() > 100) {
                throw new IllegalArgumentException("Shorts title must not exceed 100 characters");
            }
            if (description != null && description.length() > 1000) {
                throw new IllegalArgumentException("Shorts description must not exceed 1000 characters");
            }
        } else {
            if (title.length() > 100) {
                throw new IllegalArgumentException("Video title must not exceed 100 characters");
            }
            if (description != null && description.length() > 5000) {
                throw new IllegalArgumentException("Video description must not exceed 5000 characters");
            }
        }

        if (privacyStatus == null || (!privacyStatus.equals("private") &&
                !privacyStatus.equals("public") && !privacyStatus.equals("unlisted"))) {
            throw new IllegalArgumentException("Privacy status must be private, public, or unlisted");
        }
    }

    // == NESTED CLASSES ==

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class RecordingDetailsDTO {
        @JsonProperty("location_description")
        private String locationDescription;

        @JsonProperty("recording_date")
        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
        private LocalDate recordingDate;
    }
}