version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ytms-postgres
    environment:
      POSTGRES_DB: ytms_db
      POSTGRES_USER: ytms_user
      POSTGRES_PASSWORD: ytms_password
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ytms_user -d ytms_db" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ytms-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ytms.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: